
primary     = 'null' | BOOL | CHAR
            | NUMBER | STRING
            | '(' expression ')'
            | IDENTIFIER ;

type        = IDENTIFIER
            | IDENTIFIER '[' (LITERAL | type)+ ']';

tupleinit   = '(' expression (',' expression)+  ')';
memberinit  = '.' IDENTIFIER ':' expression;
nametuple   = '{' memberinit (',' memberinit)
initializer = expression | '['
declaration = ('mut' | 'iu') IDENTIFIER type? ('=' initializer)

program     = { declaration } ;